### ISSUE TITLE
not working on Linux (easy fix)

### ISSUE THREAD

**Issue by AnimaMachina** [DeBullVader/BU_Blender_AssetLibrary_Plugin#1]
1. The addon doesn't work on Linux (error on registration of module).

But it can easy be fixed.
on opearators/library_download.py, on line 30,
remplace content :
`if platform.system() == "Darwin":`
by :
`if platform.system() == "Darwin" or "Linux":`

After addon can register, asset folder path can be set, download work
I tester on the last 0.1.5 version.

2. After the download, the zip files seems not to be extracted ...? So the blender_assets.cats.txt is not found by blender an doesn't list assets paths, nor assets in blend files (not extracted too).

3. Seems to be a small typo error too on function name :
heck_excist() => heck_exist()

Nice work for the content 😀️

**Comment by DeBullVader** [comment]
Thanks for the feedback! I'm reworking the download code these issues should be fixed soon. I'll have to setup some vm's to be able to test on Linux and Mac. 

Next update will also check for date time difference on assets to download them when an asset has been updated. 

Again thanks for the feedback it's much appreciated!

**Comment by AnimaMachina** [comment]
No problem

The extraction problem of zip files is because of folder separator ...
I just see now all my files are extracted on folder with strange name :

`<asset root>\<archive 1>`
`<asset root>\<archive 2>`

the problem seems to come from the portion of code where there is :
`'\\' + fileName `

(there is a portion of code with folder separator with '/' for Darwin/Linux but commented.
Perhaps if you only use a :
`core_lib.path + os.sep + fileName`

it will work ?
So the path is constructed independently of the OS on which python code run (os.sep depends of the OS, os.path.sep seems to be for root path) ...

**Comment by DeBullVader** [comment]
Ah great will try that out. Thanks!
