### ISSUE TITLE
Click checkbox enable is error bug Blender 4.1.0 Beta.

### ISSUE THREAD

**Issue by mac4kent** [DeBullVader/BU_Blender_AssetLibrary_Plugin#12]
MacOS 13.6.4
Blender 4.1.0 Beta
Please fix your code match to click check box turn on enable.
See picture 
https://imgur.com/Pmu56nF

**Comment by DeBullVader** [comment]
Unfortunately 4.1 is not supported yet. Latest supported version is 4.0

As soon as a reasonable 4.1.x stable version is out we will upgrade to
that. Blender is changing many API code. So changing on each beta would be
to time consuming

Kind regards,

DeBullVader
Dev @BlenderUniverse

Op vr 16 feb. 2024 05:36 schreef mac4kent ***@***.***>:

**Comment by mac4kent** [comment]
No I disagree with you said "Unfortunately" sorry.
You can do that on fix code to all worked Blender 4.0, 4.1, and 4.2 too. 

Nutti did great good job all version as well see https://github.com/nutti/Screencast-Keys
support 3.4 - 4.2.0 very well. Nutti do use Windows, Macintosh both it worked. 

Why not you can fix everything please not matter what you can.

**Comment by DeBullVader** [comment]
Upgrading to newer versions is on our to-do list. Currently we are preparing the code base for premium. After that we most likely will look in to newer versions.

**Comment by mac4kent** [comment]
Sure NP
