### ISSUE TITLE
No assets showing

### ISSUE THREAD

**Issue by jamesfc** [DeBullVader/BU_Blender_AssetLibrary_Plugin#13]
I've installed the latest version in Blender 3.6 and 4.02 but I'm not getting any assets showing in either version.  In the asset manager when I click on the sync button I just get an error message.

**Comment by DeBullVader** [comment]
Thank you for reaching out!
What kind of error are you recieving.

If you like you can join our discord and create a ticket there.
https://discord.gg/bakeduniverse

It will make it easier for us to help with any issue

Op zo 25 feb. 2024 01:27 schreef jamesfc ***@***.***>:
