### ISSUE TITLE
Click checkbox to be enable error on Blender 4.1.0

### ISSUE THREAD

**Issue by mac4kent** [DeBullVader/BU_Blender_AssetLibrary_Plugin#14]
Your add-ons not work for Blender 4.1.0
Please fix everything to be enable (checkbox)

**Comment by DeBullVader** [comment]
We are currently in the process of releasing our premium library. Which
will be released in 4 days. After this I will be looking in to migrating to
4.1

I will have to see what changes need to be made to support 4.1

As far as I have seen it should be relatively easy to support 4.1 so please
stay tuned it's on the agenda!

Kind Regards,

DeBullVader,
Technical Artist at Blender-Universe

Op do 28 mrt. 2024 18:29 schreef mac4kent ***@***.***>:

**Comment by mac4kent** [comment]
Allright thanks
