### ISSUE TITLE
blender_assets.cats.txt unzip on wrond folder

### ISSUE THREAD

**Issue by AnimaMachina** [DeBullVader/BU_Blender_AssetLibrary_Plugin#3]
On the last code (v.0.1.7),
after the new recent update (grassify), the check of update needed is correctly made. The new asset is correctly unzipped, the need of update of blender catalog is correctly made (new blender_assets.cats.txt, because grassify use a new catalog folder ID inside it).
=> But the "blender_assets.cats.txt" file is unzipped on wrong folder.
It is unzipped on "BU_User_Upload" subfolder, and not on the "BU_AssetLibrary_Core" which is his root parent. So the blender catalog is on the subfolder, the asset library can't update the catalog classification ID.

**Comment by DeBullVader** [comment]
That's strange as the one in the upload folder should be a copy of the one in the core folder. I'll look in to it!
