### ISSUE TITLE
Asset browser not working

### ISSUE THREAD

**Issue by ChavdarKostadinov98** [DeBullVader/BU_Blender_AssetLibrary_Plugin#5]
Hello,

after setting up the folder for the assets to be downloaded, when I expand the add-on and try to enter the dropdown menu that says Baked suite asset browser tool, I don't see any button, just paragraphs of text which is not fully shown unfortunately so I cant see what it says, but I think it's some kind of instructions. Any ideas why this might be ?

Thank you!

**Comment by DeBullVader** [comment]
Hey! You should be able to scroll down and see the rest of the settings. 

 Note that the minimum required blender version is 3.5

It might be useful to join our discord and open a ticket. It will be easier to debug the issue. 

https://discord.gg/bakeduniverse

It's currently late here so if nobody has picked up your ticket before I return I'll pick it up tomorrow asap.
