### ISSUE TITLE
Why Google Services API download for Blender addon?

### ISSUE THREAD

**Issue by pokeslog** [DeBullVader/BU_Blender_AssetLibrary_Plugin#6]
Pretty crappy that I find GoogleAPICLIENT downloaded as part of your addon, along with A LOT of other shady things.     You created an _init_.py in the discovery_cache of the 4.0\scripts\addons\Baked_Blender_Suite\dependencies\windows\googleapiclient\discovery_cache.  You can use that to pull data.    

STAY AWAY FROM THIS.  NO ADDON NEEDS GOOGLE API ACCESS.  NONE.

**Comment by DeBullVader** [comment]
We use a service account to communicate with our own folder that holds the assets. There is no user authentication whatsoever.
The init.py file is part of a dependency that installs when you install google api with npm. 
We basically use our service account to fetch the file id of the assets in specific folders on our own drive. Our service account has has access only to those folder.

**Comment by DeBullVader** [comment]
I'm fine with you asking questions. But i do not accept the way you word your questions. Please be mindful of that!
